=== FrancineB/kwapi/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="config" type="config">
	<xs:unique name="driverClass">
		<xs:selector xpath="./driver"/>
		<xs:field xpath="@class"/>
	</xs:unique>
	<xs:unique name="probeID">
		<xs:selector xpath="./driver/probe"/>
		<xs:field xpath="@id"/>
	</xs:unique>
</xs:element>

<xs:complexType name="config">
	<xs:sequence>
		<xs:element name="collector" type="collector"/>
		<xs:element name="driver" type="driver" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="collector">
	<xs:attribute name="socket" type="xs:string"/>
</xs:complexType>

<xs:complexType name="driver">
	<xs:sequence>
		<xs:element name="probe" type="probe" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="class" type="xs:NCName"/>
</xs:complexType>

<xs:complexType name="probe">
    <xs:sequence>
		<xs:element name="arg" type="arg" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="id" type="xs:NCName"/>
</xs:complexType>

<xs:complexType name="arg">
	<xs:attribute name="name" type="xs:string"/>
	<xs:attribute name="value" type="xs:string"/>
</xs:complexType>

</xs:schema>

=== FrancineB/kwapi/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

	<collector socket="/tmp/kwapi-collector"/>
	
	<driver class="Wattsup">
		<probe id="A">
			<arg name="device" value="/dev/ttyUSB0"/>
		</probe>
<!--		<probe id="B">-->
<!--			<arg name="device" value="/dev/ttyUSB1"/>-->
<!--		</probe>-->
	</driver>
	
<!--	<driver class="Omega">-->
<!--		<probe id="C">-->
<!--			<arg name="IP" value="192.168.0.10"/>-->
<!--			<arg name="port" value="2020"/>-->
<!--			<arg name="output" value="1"/>-->
<!--		</probe>-->
<!--		<probe id="D">-->
<!--			<arg name="IP" value="192.168.0.10"/>-->
<!--			<arg name="port" value="2020"/>-->
<!--			<arg name="output" value="1"/>-->
<!--		</probe>-->
<!--	</driver>-->
	
	<driver class="Dummy">
		<probe id="X"/>
		<probe id="Y">
			<arg name="min_value" value="10"/>
			<arg name="max_value" value="20"/>
		</probe>
	</driver>

</config>
